### PR TITLE
add missing namespace to code example

### PR DESCRIPTION
**Pull request by schultyy**
I noticed the namespace is missing here and for users who are not using an IDE they might have to go through the source code to look it up otherwise.

### CODE REVIEW

**Comment by tvaintrob** [comment]
thanks for the input!
please fix commit message format so i can approve the PR

**Comment by schultyy** [comment]
@tvaintrob Done! Does the message look good?

**Comment by tvaintrob** [comment]
Please refer to the commit lint action for instructions, thanks!

**Comment by tvaintrob** [comment]
Please refer to the commit lint action for instructions, thanks!

**Pull request closed without merging**
